### ISSUE TITLE
Rendu TP (2e édition)

### ISSUE THREAD

**Issue by pierreelliott** [PolytechLyon/2019-isi3-graph-perier_thiboud_tp1#2]
Bonjour,

Nous avons supprimé ce vilain garnement qui s'était infiltré dans notre code (cf6830ed538d0799d4dc8615e0f48312412c9fa0).  
Nous sommes donc prêt à (re)subir votre jugement.

J'en profite pour vous poser une question, afin d'être sûr d'avoir bien compris. 
L'opérateur "<>" dans <pre>Iterator\<Node\></pre> signifie que l'objet Iterator effectue ses opérations sur des objets de types **Node** (ou descendant).
Donc lorsque **GraphIterator** implémente **Iterator<Node>**, cela veut dire que c'est un **Iterator** qui ne peut effectuer ses actions que sur des objets de type **Node** ?
https://github.com/PolytechLyon/2019-isi3-graph-perier_thiboud_tp1/blob/cf6830ed538d0799d4dc8615e0f48312412c9fa0/src/main/java/graph/iterators/GraphIterator.java#L11

**Comment by Slashgear** [comment]
Yep
